[features]
seeds = false

[programs.localnet]
solstake = "4N9p69ju8BtQCLZ96DgCQ8cXHgmebiwhHhCyMxVkNU7R"

[programs.devnet]
solstake = "4N9p69ju8BtQCLZ96DgCQ8cXHgmebiwhHhCyMxVkNU7R"

[programs.mainnet]
solstake = "4N9p69ju8BtQCLZ96DgCQ8cXHgmebiwhHhCyMxVkNU7R"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/solminer.ts"
